// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lottery} from '../models';

export function DrawWinners(arg1:number):Promise<Array<lottery.User>>;

export function SetBiliCookie(arg1:string):Promise<void>;

export function StartCollect(arg1:string):Promise<void>;

export function StartDanmaku(arg1:number):Promise<void>;

export function StopCollect():Promise<void>;

export function StopDanmaku():Promise<void>;
