// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DrawWinners(arg1) {
  return window['go']['main']['App']['DrawWinners'](arg1);
}

export function SetBiliCookie(arg1) {
  return window['go']['main']['App']['SetBiliCookie'](arg1);
}

export function StartCollect(arg1) {
  return window['go']['main']['App']['StartCollect'](arg1);
}

export function StartDanmaku(arg1) {
  return window['go']['main']['App']['StartDanmaku'](arg1);
}

export function StopCollect() {
  return window['go']['main']['App']['StopCollect']();
}

export function StopDanmaku() {
  return window['go']['main']['App']['StopDanmaku']();
}
