// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPrize():Promise<string>;

export function CheckQRCodeStatus(arg1:string):Promise<string>;

export function GetAccountInfo():Promise<string>;

export function GetConfig():Promise<string>;

export function GetQRCode():Promise<string>;

export function IsRunning():Promise<boolean>;

export function Login(arg1:string):Promise<string>;

export function LoginWithQRCode(arg1:string):Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function StartLottery():Promise<string>;

export function StopLottery():Promise<void>;
