// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPrize() {
  return window['go']['main']['App']['CheckPrize']();
}

export function CheckQRCodeStatus(arg1) {
  return window['go']['main']['App']['CheckQRCodeStatus'](arg1);
}

export function ConnectLiveRoom(arg1) {
  return window['go']['main']['App']['ConnectLiveRoom'](arg1);
}

export function DrawWinners(arg1) {
  return window['go']['main']['App']['DrawWinners'](arg1);
}

export function GetAccountInfo() {
  return window['go']['main']['App']['GetAccountInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetParticipantCount() {
  return window['go']['main']['App']['GetParticipantCount']();
}

export function GetQRCode() {
  return window['go']['main']['App']['GetQRCode']();
}

export function IsLiveLotteryRunning() {
  return window['go']['main']['App']['IsLiveLotteryRunning']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function LoginWithQRCode(arg1) {
  return window['go']['main']['App']['LoginWithQRCode'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartLiveLottery(arg1) {
  return window['go']['main']['App']['StartLiveLottery'](arg1);
}

export function StartLottery() {
  return window['go']['main']['App']['StartLottery']();
}

export function StopLiveLottery() {
  return window['go']['main']['App']['StopLiveLottery']();
}

export function StopLottery() {
  return window['go']['main']['App']['StopLottery']();
}
