// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWatchedRoom(arg1:number):Promise<void>;

export function CheckPrize():Promise<string>;

export function CheckQRCodeStatus(arg1:string):Promise<string>;

export function ConnectLiveRooms(arg1:Array<number>):Promise<void>;

export function DrawWinners(arg1:number):Promise<string>;

export function GetAccountInfo():Promise<string>;

export function GetBackgroundImage():Promise<string>;

export function GetConfig():Promise<string>;

export function GetParticipantCount():Promise<number>;

export function GetQRCode():Promise<string>;

export function GetWatchedRooms():Promise<string>;

export function IsLiveLotteryRunning():Promise<boolean>;

export function IsLoggedIn():Promise<boolean>;

export function IsRunning():Promise<boolean>;

export function Login(arg1:string):Promise<string>;

export function LoginWithQRCode(arg1:string):Promise<string>;

export function Logout():Promise<void>;

export function RemoveWatchedRoom(arg1:number):Promise<void>;

export function SaveConfig(arg1:string):Promise<void>;

export function SetBackgroundImage(arg1:string):Promise<void>;

export function StartLiveLottery(arg1:string):Promise<void>;

export function StartLottery():Promise<string>;

export function StopLiveLottery():Promise<void>;

export function StopLottery():Promise<void>;
